[package]
name = "states-ui-test"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", features = ["bevy_dev_tools"] }

[profile.dev.package."*"]
debug = false
opt-level = 3
debug-assertions = false
overflow-checks = false
